services:
  - type: web
    name: babylon-game-starter
    env: docker
    plan: free
    region: maine
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production